# application.yml
spring:
  application:
    name: wodMarket

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 10MB

  comm:
    upload:
      path: /Users/dawon/temp/

